/*
 * Copyright 2026 alexisbinh
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.alexisbinh.tools;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.bukkit.entity.EntityType;

/**
 * Gradle {@code generateDefaultConfig}: writes a minimal default {@code config.yml}. No Paper server required.
 */
public final class GenerateDefaults {

    private static final List<String> DEFAULT_BLOCK_LIST = List.of(
            "HOPPER",
            "PISTON",
            "STICKY_PISTON",
            "OBSERVER",
            "DISPENSER",
            "DROPPER"
    );

    private static final int[] DEFAULT_BLOCK_LIMITS = {12, 16, 16, 12, 16, 16};

    private GenerateDefaults() {}

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            throw new IllegalArgumentException("usage: GenerateDefaults <path-to-config.yml>");
        }
        Path out = Path.of(args[0]);
        StringBuilder sb = new StringBuilder();
        sb.append("# LagProtector — default config (generated by generateDefaultConfig; tune for your server).\n\n");
        sb.append("debug: false\n\n");
        sb.append("Log:\n  Enabled: false\n  From: 3\n\n");
        sb.append("Ignore:\n");
        sb.append("  FullArmorStands: true\n");
        sb.append("  EntityWithPickedItem: true\n");
        sb.append("  FullItemFrames: true\n");
        sb.append("  TamedAnimals: true\n");
        sb.append("  NamedAnimals: true\n");
        sb.append("  WithSadle: true\n");
        sb.append("  BabyAnimals: true\n");
        sb.append("  Worlds: []\n\n");
        sb.append("EntitySpawn:\n");
        sb.append("  Check: true\n");
        sb.append("  GroupChunks: true\n");
        sb.append("  # 1 = 1 chunk, 2 = 3x3 (9), 3 = 5x5 (25)\n");
        sb.append("  GroupChunksRadius: 2\n\n");
        sb.append("ExcludedChunks: []\n\n");
        sb.append("Mobs:\n  WorldsAllow: []\n");
        sb.append("  # Default cap for mob-cap types not listed under EntityTypes. -1: only types explicitly listed are limited.\n");
        sb.append("  DefaultPerType: 28\n");
        sb.append("  # Shared cap for non-mob-cap types without an EntityTypes row (spawn + cull). -1: disabled.\n");
        sb.append("  FallbackNonLivingLimit: -1\n");
        sb.append("  TotalMaxPerChunk: -1\n\n");
        sb.append("AutoClean:\n");
        sb.append("  Enabled: false\n");
        sb.append("  Mobs:\n    Use: false\n    Interval: 20\n    MaxRemoved: 48\n");
        sb.append("    SliceChunksPerTick: 64\n    DeduplicateGroupCull: true\n");
        sb.append("  Blocks:\n    Use: false\n    Interval: 20\n    MaxRemoved: 12\n    BreakNaturally: false\n");
        sb.append("    SliceChunksPerTick: 64\n\n");
        sb.append("BlockTypes:\n  Limit: true\n  CheckPistonMove: true\n  List:\n");
        for (int i = 0; i < DEFAULT_BLOCK_LIST.size(); i++) {
            sb.append("    ").append(DEFAULT_BLOCK_LIST.get(i)).append(": ").append(DEFAULT_BLOCK_LIMITS[i]).append('\n');
        }
        sb.append("\nEntityTypes:\n");
        appendEntityType(sb, EntityType.PLAYER, -1, false);
        appendEntityType(sb, EntityType.ITEM, 150, true);
        appendEntityType(sb, EntityType.EXPERIENCE_ORB, 75, true);
        appendEntityType(sb, EntityType.ITEM_FRAME, 24, true);
        appendEntityType(sb, EntityType.GLOW_ITEM_FRAME, 24, true);
        appendEntityType(sb, EntityType.HOPPER_MINECART, 4, true);
        Files.writeString(out, sb.toString(), StandardCharsets.UTF_8);
    }

    private static void appendEntityType(StringBuilder sb, EntityType type, int limit, boolean autoClean) {
        sb.append("  ").append(type.name()).append(":\n");
        sb.append("    Use: true\n");
        sb.append("    Limit: ").append(limit).append('\n');
        sb.append("    AutoClean: ").append(autoClean).append('\n');
        sb.append("    NaturalSpawn: true\n");
    }
}
